'use strict';

window.D3GRPH = window.D3GRPH || {};

window.D3GRPH._data.homepageGraphs = [
    {
        "id":1,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"meta",
                "text":"relation-type",
                "x":0.8,
                "y":0.15
            },
            {
                "id":1,
                "type":"relation-type",
                "text":"director-ship",
                "x":0.5,
                "y":0.1
            },
            {
                "id":2,
                "type":"relation",
                "text":"•",
                "x":0.3,
                "y":0.267
            },
            {
                "id":3,
                "type":"relation",
                "text":"•",
                "x":0.7,
                "y":0.267
            },
            {
                "id":4,
                "type":"instance",
                "text":"$x: Titanic",
                "x":0.1,
                "y":0.533
            },
            {
                "id":5,
                "type":"instance",
                "text":"$y: James Cameron",
                "x":0.5,
                "y":0.533
            },
            {
                "id":6,
                "type":"instance",
                "text":"$z: Avatar",
                "x":0.9,
                "y":0.533
            },
            {
                "id":7,
                "type":"concept-type",
                "text":"person",
                "x":0.15,
                "y":0.8
            },
            {
                "id":8,
                "type":"concept-type",
                "text":"movie",
                "x":0.85,
                "y":0.8
            },
            {
                "id":9,
                "type":"meta",
                "text":"concept-type",
                "x":0.5,
                "y":0.9
            }
        ],
        "edges":[
            {
                "source":1,
                "target":0,
                "text":"isa"
            },
            {
                "source":2,
                "target":1,
                "text":"isa"
            },
            {
                "source":3,
                "target":1,
                "text":"isa"
            },
            {
                "source":3,
                "target":5,
                "text":"director",
                "type":"active"
            },
            {
                "source":3,
                "target":6,
                "text":"movie-directed",
                "type":"active"
            },
            {
                "source":2,
                "target":4,
                "text":"movie-directed",
                "type":"active"
            },
            {
                "source":2,
                "target":5,
                "text":"director",
                "type":"active"
            },
            {
                "source":4,
                "target":8,
                "text":"isa"
            },
            {
                "source":6,
                "target":8,
                "text":"isa"
            },
            {
                "source":5,
                "target":7,
                "text":"isa"
            },
            {
                "source":7,
                "target":9,
                "text":"isa"
            },
            {
                "source":8,
                "target":9,
                "text":"isa"
            }
        ]
    },
    {
        "id":2,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"meta",
                "text":"concept-type",
                "x":0.2,
                "y":0.15
            },
            {
                "id":1,
                "type":"concept-type",
                "text":"movie",
                "x":0.1,
                "y":0.5
            },
            {
                "id":2,
                "type":"instance",
                "text":"$x: id1234",
                "x":0.2,
                "y":0.85
            },
            {
                "id":3,
                "type":"relation",
                "text":"has",
                "x":0.37,
                "y":0.1
            },
            {
                "id":4,
                "type":"relation",
                "text":"has",
                "x":0.32,
                "y":0.5
            },
            {
                "id":5,
                "type":"relation",
                "text":"has",
                "x":0.37,
                "y":0.9
            },
            {
                "id":6,
                "type":"resource",
                "text":"8.3",
                "x":0.57,
                "y":0.1
            },
            {
                "id":7,
                "type":"resource",
                "text":"The Martian",
                "x":0.5,
                "y":0.5
            },
            {
                "id":8,
                "type":"resource",
                "text":"30 Sep 2015",
                "x":0.57,
                "y":0.9
            },
            {
                "id":9,
                "type":"resource-type",
                "text":"rating",
                "x":0.8,
                "y":0.15
            },
            {
                "id":10,
                "type":"resource-type",
                "text":"title",
                "x":0.7,
                "y":0.5
            },
            {
                "id":11,
                "type":"resource-type",
                "text":"release-date",
                "x":0.8,
                "y":0.85
            },
            {
                "id":12,
                "type":"meta",
                "text":"resource-type",
                "x":0.9,
                "y":0.5
            }
        ],
        "edges":[
            {
                "source":1,
                "target":0,
                "text":"isa"
            },
            {
                "source":2,
                "target":1,
                "text":"isa",
                "type":"active"
            },
            {
                "source":3,
                "target":2,
                "text":"owner"
            },
            {
                "source":4,
                "target":2,
                "text":"owner",
                "type":"active"
            },
            {
                "source":5,
                "target":2,
                "text":"owner"
            },
            {
                "source":3,
                "target":6,
                "text":"value"
            },
            {
                "source":4,
                "target":7,
                "text":"value",
                "type":"active"
            },
            {
                "source":5,
                "target":8,
                "text":"value"
            },
            {
                "source":6,
                "target":9,
                "text":"isa"
            },
            {
                "source":7,
                "target":10,
                "text":"isa",
                "type":"active"
            },
            {
                "source":8,
                "target":11,
                "text":"isa"
            },
            {
                "source":9,
                "target":12,
                "text":"isa"
            },
            {
                "source":10,
                "target":12,
                "text":"isa"
            },
            {
                "source":11,
                "target":12,
                "text":"isa"
            }
        ]
    },
    {
        "id":3,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"meta",
                "text":"relation-type",
                "x":0.5,
                "y":0.1
            },
            {
                "id":1,
                "type":"relation-type",
                "text":"director-ship",
                "x":0.2,
                "y":0.2
            },
            {
                "id":2,
                "type":"relation-type",
                "text":"casting",
                "x":0.8,
                "y":0.2
            },
            {
                "id":3,
                "type":"relation",
                "text":"•",
                "x":0.3,
                "y":0.36
            },
            {
                "id":4,
                "type":"relation",
                "text":"•",
                "x":0.7,
                "y":0.36
            },
            {
                "id":5,
                "type":"instance",
                "text":"$z: Ang Lee",
                "x":0.1,
                "y":0.56
            },
            {
                "id":6,
                "type":"instance",
                "text":"$y: Life of Pi",
                "x":0.5,
                "y":0.56
            },
            {
                "id":7,
                "type":"instance",
                "text":"$y: Irrfan Khan",
                "x":0.9,
                "y":0.56
            },
            {
                "id":8,
                "type":"concept-type",
                "text":"person",
                "x":0.2,
                "y":0.8
            },
            {
                "id":9,
                "type":"concept-type",
                "text":"movie",
                "x":0.8,
                "y":0.8
            },
            {
                "id":10,
                "type":"meta",
                "text":"concept-type",
                "x":0.5,
                "y":0.9
            }
        ],
        "edges":[
            {
                "source":1,
                "target":0,
                "text":"isa"
            },
            {
                "source":2,
                "target":0,
                "text":"isa"
            },
            {
                "source":3,
                "target":1,
                "text":"isa"
            },
            {
                "source":3,
                "target":5,
                "text":"director",
                "type":"active"
            },
            {
                "source":3,
                "target":6,
                "text":"movie-directed",
                "type":"active"
            },
            {
                "source":4,
                "target":2,
                "text":"isa"
            },
            {
                "source":4,
                "target":6,
                "text":"movie-cast",
                "type":"active"
            },
            {
                "source":4,
                "target":7,
                "text":"actor",
                "type":"active"
            },
            {
                "source":7,
                "target":8,
                "text":"isa"
            },
            {
                "source":6,
                "target":9,
                "text":"isa"
            },
            {
                "source":5,
                "target":8,
                "text":"isa"
            },
            {
                "source":9,
                "target":10,
                "text":"isa"
            },
            {
                "source":8,
                "target":10,
                "text":"isa"
            }
        ]
    },
    {
        "id":4,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"meta",
                "text":"concept-type",
                "x":0.2,
                "y":0.15
            },
            {
                "id":1,
                "type":"concept-type",
                "text":"movie",
                "x":0.1,
                "y":0.5
            },
            {
                "id":2,
                "type":"instance",
                "text":"$x",
                "x":0.2,
                "y":0.85
            },

            {
                "id":3,
                "type":"relation",
                "text":"has",
                "x":0.4,
                "y":0.1
            },
            {
                "id":4,
                "type":"relation",
                "text":"has",
                "x":0.367,
                "y":0.5
            },
            {
                "id":5,
                "type":"relation",
                "text":"has",
                "x":0.4,
                "y":0.9
            },
            {
                "id":6,
                "type":"resource",
                "text":"Friday the 13th",
                "x":0.6,
                "y":0.1
            },
            {
                "id":7,
                "type":"resource",
                "text":"Slasher",
                "x":0.633,
                "y":0.5
            },
            {
                "id":8,
                "type":"resource",
                "text":"Horror",
                "x":0.6,
                "y":0.9
            },
            {
                "id":9,
                "type":"resource-type",
                "text":"title",
                "x":0.8,
                "y":0.15
            },
            {
                "id":10,
                "type":"meta",
                "text":"resource-type",
                "x":0.9,
                "y":0.5
            },
            {
                "id":11,
                "type":"resource-type",
                "text":"genre",
                "x":0.8,
                "y":0.85
            }
        ],
        "edges":[
            {
                "source":1,
                "target":0,
                "text":"isa"
            },
            {
                "source":2,
                "target":1,
                "text":"isa"
            },
            {
                "source":3,
                "target":2,
                "text":"owner"
            },
            {
                "source":4,
                "target":2,
                "text":"owner"
            },
            {
                "source":5,
                "target":2,
                "text":"owner",
                "type":"active"
            },
            {
                "source":3,
                "target":6,
                "text":"value"
            },
            {
                "source":4,
                "target":7,
                "text":"value"
            },
            {
                "source":5,
                "target":8,
                "text":"value",
                "type":"active"
            },
            {
                "source":6,
                "target":9,
                "text":"isa"
            },
            {
                "source":7,
                "target":11,
                "text":"isa"
            },
            {
                "source":8,
                "target":11,
                "text":"isa",
                "type":"active"
            },
            {
                "source":9,
                "target":10,
                "text":"isa"
            },
            {
                "source":11,
                "target":10,
                "text":"isa"
            }
        ]
    },
    {
        "id":5,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"meta",
                "text":"concept-type",
                "x":0.18,
                "y":0.2
            },
            {
                "id":1,
                "type":"meta",
                "text":"relation-type",
                "x":0.5,
                "y":0.1
            },
            {
                "id":2,
                "type":"relation-type",
                "text":"director-ship",
                "x":0.82,
                "y":0.2
            },
            {
                "id":3,
                "type":"concept-type",
                "text":"movie",
                "x":0.1,
                "y":0.6
            },
            {
                "id":4,
                "type":"relation",
                "text":"$z",
                "x":0.5,
                "y":0.6
            },
            {
                "id":5,
                "type":"concept-type",
                "text":"person",
                "x":0.9,
                "y":0.6
            },
            {
                "id":6,
                "type":"instance",
                "text":"$x: Big Fish",
                "x":0.3,
                "y":0.9
            },
            {
                "id":7,
                "type":"instance",
                "text":"$y: Tim Burton",
                "x":0.7,
                "y":0.9
            }
        ],
        "edges":[
            {
                "source":2,
                "target":1,
                "text":"isa"
            },
            {
                "source":3,
                "target":0,
                "text":"isa"
            },
            {
                "source":4,
                "target":2,
                "text":"isa"
            },
            {
                "source":4,
                "target":6,
                "text":"movie-directed",
                "type":"active"
            },
            {
                "source":4,
                "target":7,
                "text":"director",
                "type":"active"
            },
            {
                "source":5,
                "target":0,
                "text":"isa"
            },
            {
                "source":6,
                "target":3,
                "text":"isa",
                "type":"active"
            },
            {
                "source":7,
                "target":5,
                "text":"isa",
                "type":"active"
            }
        ]
    }
];

window.D3GRPH._data.platformGraphs = [
    {
        "id": 1,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"concept-type",
                "text":"person",
                "x":0.5,
                "y":0.1
            },
            {
                "id":1,
                "type":"instance",
                "text":"Alice",
                "x":0.1,
                "y":0.9
            },
            {
                "id":2,
                "type":"instance",
                "text":"Bob",
                "x":0.9,
                "y":0.9
            }
        ],
        "edges":[
            {
                "source":1,
                "target":0,
                "text":"isa"
            },
            {
                "source":2,
                "target":0,
                "text":"isa"
            }
        ]
    },
    {
        "id": 2,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"concept-type",
                "text":"person",
                "x":0.1,
                "y":0.1
            },
            {
                "id":1,
                "type":"instance",
                "text":"Alice",
                "x":0.1,
                "y":0.9
            },
            {
                "id":2,
                "type":"instance",
                "text":"Honesty Inc.",
                "x":0.9,
                "y":0.9
            },
            {
                "id":3,
                "type":"relation",
                "text":"•",
                "x":0.5,
                "y":0.5
            },
            {
                "id":4,
                "type":"concept-type",
                "text":"company",
                "x":0.9,
                "y":0.1
            },
            {
                "id":5,
                "type":"relation-type",
                "text":"director-ship",
                "x":0.5,
                "y":0.1
            }
        ],
        "edges":[
            {
                "source":1,
                "target":0,
                "text":"isa"
            },
            {
                "source":2,
                "target":4,
                "text":"isa"
            },
            {
                "source":3,
                "target":2,
                "text":"directed"
            },
            {
                "source":3,
                "target":1,
                "text":"director"
            },
            {
                "source":3,
                "target":5,
                "text":"isa"
            }
        ]
    },
    {
        "id": 3,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"relation-type",
                "text":"marriage",
                "x":0.5,
                "y":0.1
            },
            {
                "id":1,
                "type":"role-type",
                "text":"wife",
                "x":0.1,
                "y":0.3
            },
            {
                "id":2,
                "type":"role-type",
                "text":"husband",
                "x":0.9,
                "y":0.3
            },
            {
                "id":3,
                "type":"instance",
                "text":"Alice",
                "x":0.1,
                "y":0.7
            },
            {
                "id":4,
                "type":"relation",
                "text":"•",
                "x":0.5,
                "y":0.5
            },
            {
                "id":5,
                "type":"instance",
                "text":"Bob",
                "x":0.9,
                "y":0.7
            },
            {
                "id":6,
                "type":"concept-type",
                "text":"person",
                "x":0.5,
                "y":0.9
            }
        ],
        "edges":[
            {
                "source":0,
                "target":1,
                "text":"has role"
            },
            {
                "source":0,
                "target":2,
                "text":"has role"
            },
            {
                "source":4,
                "target":0,
                "text":"isa"
            },
            {
                "source":4,
                "target":3,
                "text":"wife"
            },
            {
                "source":4,
                "target":5,
                "text":"husband"
            },
            {
                "source":3,
                "target":6,
                "text":"isa"
            },
            {
                "source":5,
                "target":6,
                "text":"isa"
            }
        ]
    },
    {
        "id": 4,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"relation-type",
                "text":"director-ship",
                "x":0.5,
                "y":0.1
            },
            {
                "id":1,
                "type":"role-type",
                "text":"director",
                "x":0.1,
                "y":0.1
            },
            {
                "id":2,
                "type":"role-type",
                "text":"directed",
                "x":0.9,
                "y":0.1
            },
            {
                "id":3,
                "type":"instance",
                "text":"Alice",
                "x":0.3,
                "y":0.9
            },
            {
                "id":4,
                "type":"relation",
                "text":"•",
                "x":0.5,
                "y":0.5
            },
            {
                "id":5,
                "type":"instance",
                "text":"Honesty Inc.",
                "x":0.7,
                "y":0.9
            },
            {
                "id":6,
                "type":"concept-type",
                "text":"person",
                "x":0.1,
                "y":0.55
            },
            {
                "id":7,
                "type":"concept-type",
                "text":"company",
                "x":0.9,
                "y":0.55
            }
        ],
        "edges":[
            {
                "source":0,
                "target":1,
                "text":"has role"
            },
            {
                "source":0,
                "target":2,
                "text":"has role"
            },
            {
                "source":4,
                "target":0,
                "text":"isa"
            },
            {
                "source":4,
                "target":3,
                "text":"director"
            },
            {
                "source":4,
                "target":5,
                "text":"directed"
            },
            {
                "source":3,
                "target":6,
                "text":"isa"
            },
            {
                "source":5,
                "target":7,
                "text":"isa"
            },
            {
                "source":6,
                "target":1,
                "text":"plays role"
            },
            {
                "source":7,
                "target":2,
                "text":"plays role"
            }
        ]
    },
    {
        "id": 5,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"relation-type",
                "text":"director-ship",
                "x":0.5,
                "y":0.1
            },
            {
                "id":1,
                "type":"role-type",
                "text":"director",
                "x":0.1,
                "y":0.5
            },
            {
                "id":2,
                "type":"role-type",
                "text":"directed",
                "x":0.9,
                "y":0.5
            },
            {
                "id":3,
                "type":"concept-type",
                "text":"person",
                "x":0.1,
                "y":0.9
            },
            {
                "id":4,
                "type":"concept-type",
                "text":"company",
                "x":0.9,
                "y":0.9
            },
            {
                "id":5,
                "type":"meta",
                "text":"relation-type",
                "x":0.9,
                "y":0.1
            },
            {
                "id":6,
                "type":"meta",
                "text":"role-type",
                "x":0.5,
                "y":0.5
            },
            {
                "id":7,
                "type":"meta",
                "text":"concept-type",
                "x":0.5,
                "y":0.9
            }
        ],
        "edges":[
            {
                "source":0,
                "target":1,
                "text":"has role"
            },
            {
                "source":0,
                "target":2,
                "text":"has role"
            },
            {
                "source":3,
                "target":1,
                "text":"plays role"
            },
            {
                "source":4,
                "target":2,
                "text":"plays role"
            },
            {
                "source":0,
                "target":5,
                "text":"isa"
            },
            {
                "source":1,
                "target":6,
                "text":"isa"
            },
            {
                "source":2,
                "target":6,
                "text":"isa"
            },
            {
                "source":3,
                "target":7,
                "text":"isa"
            },
            {
                "source":4,
                "target":7,
                "text":"isa"
            }
        ]
    },
    {
        "id": 6,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"relation-type",
                "text":"director-ship",
                "x":0.5,
                "y":0.1
            },
            {
                "id":1,
                "type":"role-type",
                "text":"director",
                "x":0.1,
                "y":0.1
            },
            {
                "id":2,
                "type":"role-type",
                "text":"directed",
                "x":0.9,
                "y":0.1
            },
            {
                "id":3,
                "type":"relation-type",
                "text":"marriage",
                "x":0.5,
                "y":0.9
            },
            {
                "id":4,
                "type":"role-type",
                "text":"husband",
                "x":0.1,
                "y":0.9
            },
            {
                "id":5,
                "type":"role-type",
                "text":"wife",
                "x":0.9,
                "y":0.9
            },
            {
                "id":6,
                "type":"concept-type",
                "text":"person",
                "x":0.3,
                "y":0.5
            },
            {
                "id":7,
                "type":"concept-type",
                "text":"company",
                "x":0.7,
                "y":0.5
            }
        ],
        "edges":[
            {
                "source":0,
                "target":1,
                "text":"has role"
            },
            {
                "source":0,
                "target":2,
                "text":"has role"
            },
            {
                "source":3,
                "target":4,
                "text":"has role"
            },
            {
                "source":3,
                "target":5,
                "text":"has role"
            },
            {
                "source":6,
                "target":1,
                "text":"plays role"
            },
            {
                "source":7,
                "target":2,
                "text":"plays role"
            },
            {
                "source":6,
                "target":4,
                "text":"plays role"
            },
            {
                "source":6,
                "target":5,
                "text":"plays role"
            }
        ]
    },
    {
        "id": 7,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"relation-type",
                "text":"marriage",
                "x":0.3,
                "y":0.1
            },
            {
                "id":1,
                "type":"instance",
                "text":"Bob",
                "x":0.1,
                "y":0.633
            },
            {
                "id":2,
                "type":"relation",
                "text":"•",
                "x":0.3,
                "y":0.367
            },
            {
                "id":3,
                "type":"instance",
                "text":"Alice",
                "x":0.5,
                "y":0.633
            },
            {
                "id":4,
                "type":"concept-type",
                "text":"person",
                "x":0.3,
                "y":0.9
            },
            {
                "id":5,
                "type":"relation",
                "text":"•",
                "x":0.7,
                "y":0.367
            },
            {
                "id":6,
                "type":"instance",
                "text":"Honesty Inc.",
                "x":0.9,
                "y":0.633
            },
            {
                "id":7,
                "type":"relation-type",
                "text":"director-ship",
                "x":0.7,
                "y":0.1
            },
            {
                "id":8,
                "type":"concept-type",
                "text":"company",
                "x":0.7,
                "y":0.9
            }
        ],
        "edges":[
            {
                "source":2,
                "target":0,
                "text":"isa"
            },
            {
                "source":2,
                "target":1,
                "text":"husband"
            },
            {
                "source":2,
                "target":3,
                "text":"wife"
            },
            {
                "source":1,
                "target":4,
                "text":"isa"
            },
            {
                "source":3,
                "target":4,
                "text":"isa"
            },
            {
                "source":5,
                "target":3,
                "text":"director"
            },
            {
                "source":5,
                "target":6,
                "text":"directed"
            },
            {
                "source":6,
                "target":8,
                "text":"isa"
            },
            {
                "source":5,
                "target":7,
                "text":"isa"
            }
        ]
    },
    {
        "id": 8,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"relation-type",
                "text":"marriage",
                "x":0.3,
                "y":0.1
            },
            {
                "id":1,
                "type":"instance",
                "text":"Bob",
                "x":0.1,
                "y":0.633
            },
            {
                "id":2,
                "type":"relation",
                "text":"•",
                "x":0.3,
                "y":0.367
            },
            {
                "id":3,
                "type":"instance",
                "text":"Alice",
                "x":0.5,
                "y":0.633
            },
            {
                "id":4,
                "type":"concept-type",
                "text":"person",
                "x":0.3,
                "y":0.9
            },
            {
                "id":5,
                "type":"relation",
                "text":"•",
                "x":0.7,
                "y":0.367
            },
            {
                "id":6,
                "type":"instance",
                "text":"Honesty Inc.",
                "x":0.9,
                "y":0.633
            },
            {
                "id":7,
                "type":"relation-type",
                "text":"director-ship",
                "x":0.7,
                "y":0.1
            },
            {
                "id":8,
                "type":"concept-type",
                "text":"company",
                "x":0.7,
                "y":0.9
            }
        ],
        "edges":[
            {
                "source":2,
                "target":0,
                "text":"isa"
            },
            {
                "source":2,
                "target":1,
                "text":"husband",
                "type":"active"
            },
            {
                "source":2,
                "target":3,
                "text":"wife",
                "type":"active"
            },
            {
                "source":1,
                "target":4,
                "text":"isa"
            },
            {
                "source":3,
                "target":4,
                "text":"isa"
            },
            {
                "source":5,
                "target":3,
                "text":"director",
                "type":"active"
            },
            {
                "source":5,
                "target":6,
                "text":"directed",
                "type":"active"
            },
            {
                "source":6,
                "target":8,
                "text":"isa"
            },
            {
                "source":5,
                "target":7,
                "text":"isa"
            }
        ]
    },
    {
        "id": 10,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"relation-type",
                "text":"marriage",
                "x":0.5,
                "y":0.1
            },
            {
                "id":1,
                "type":"role-type",
                "text":"husband",
                "x":0.1,
                "y":0.5
            },
            {
                "id":2,
                "type":"role-type",
                "text":"wife",
                "x":0.9,
                "y":0.5
            },
            {
                "id":3,
                "type":"concept-type",
                "text":"person",
                "x":0.5,
                "y":0.9
            }
        ],
        "edges":[
            {
                "source":0,
                "target":1,
                "text":"has role"
            },
            {
                "source":0,
                "target":2,
                "text":"has role"
            },
            {
                "source":3,
                "target":1,
                "text":"plays role"
            },
            {
                "source":3,
                "target":2,
                "text":"plays role"
            }
        ]
    },
    {
        "id": 11,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"relation",
                "text":"•",
                "x":0.5,
                "y":0.1
            },
            {
                "id":1,
                "type":"relation",
                "text":"•",
                "x":0.5,
                "y":0.9
            },
            {
                "id":2,
                "type":"instance",
                "text":"Honesty Inc.",
                "x":0.3,
                "y":0.3
            },
            {
                "id":3,
                "type":"instance",
                "text":"Evilcorp",
                "x":0.3,
                "y":0.7
            },
            {
                "id":4,
                "type":"instance",
                "text":"TrustMe.co",
                "x":0.1,
                "y":0.9
            },
            {
                "id":5,
                "type":"concept-type",
                "text":"company",
                "x":0.1,
                "y":0.5
            },
            {
                "id":6,
                "type":"instance",
                "text":"Alice",
                "x":0.7,
                "y":0.3
            },
            {
                "id":7,
                "type":"instance",
                "text":"Bob",
                "x":0.7,
                "y":0.7
            },
            {
                "id":8,
                "type":"concept-type",
                "text":"person",
                "x":0.9,
                "y":0.5
            },
            {
                "id":9,
                "type":"relation-type",
                "text":"director-ship",
                "x":0.5,
                "y":0.5
            }
        ],
        "edges":[
            {
                "source":0,
                "target":9,
                "text":"isa"
            },
            {
                "source":1,
                "target":9,
                "text":"isa"
            },
            {
                "source":2,
                "target":5,
                "text":"isa",
                "type":"active"
            },
            {
                "source":3,
                "target":5,
                "text":"isa",
                "type":"active"
            },
            {
                "source":4,
                "target":5,
                "text":"isa",
                "type":"alert"
            },
            {
                "source":0,
                "target":2,
                "text":"directed",
                "type":"active"
            },
            {
                "source":1,
                "target":3,
                "text":"directed",
                "type":"active"
            },
            {
                "source":0,
                "target":6,
                "text":"director",
                "type":"active"
            },
            {
                "source":1,
                "target":7,
                "text":"director",
                "type":"active"
            },
            {
                "source":6,
                "target":8,
                "text":"isa",
                "type":"active"
            },
            {
                "source":7,
                "target":8,
                "text":"isa",
                "type":"active"
            }
        ]
    },
    {
        "id": 12,
        "width": 562,
        "height": 400,
        "nodes":[
            {
                "id":0,
                "type":"relation-type",
                "text":"marriage",
                "x":0.5,
                "y":0.1
            },
            {
                "id":1,
                "type":"instance",
                "text":"Alice",
                "x":0.1,
                "y":0.1
            },
            {
                "id":2,
                "type":"relation",
                "text":"•",
                "x":0.5,
                "y":0.35
            },
            {
                "id":3,
                "type":"instance",
                "text":"Bob",
                "x":0.9,
                "y":0.1
            },
            {
                "id":4,
                "type":"relation",
                "text":"•",
                "x":0.35,
                "y":0.4
            },
            {
                "id":5,
                "type":"relation-type",
                "text":"director-ship",
                "x":0.7,
                "y":0.7
            },
            {
                "id":6,
                "type":"relation",
                "text":"•",
                "x":0.65,
                "y":0.4
            },
            {
                "id":7,
                "type":"instance",
                "text":"Honesty Inc.",
                "x":0.1,
                "y":0.5
            },
            {
                "id":8,
                "type":"relation-type",
                "text":"address",
                "x":0.3,
                "y":0.7
            },
            {
                "id":9,
                "type":"instance",
                "text":"Evilcorp",
                "x":0.9,
                "y":0.5
            },
            {
                "id":10,
                "type":"relation",
                "text":"•",
                "x":0.1,
                "y":0.9
            },
            {
                "id":11,
                "type":"relation",
                "text":"•",
                "x":0.9,
                "y":0.9
            },
            {
                "id":12,
                "type":"instance",
                "text":"Easy Street",
                "x":0.5,
                "y":0.9
            }
        ],
        "edges":[
            {
                "source":2,
                "target":0,
                "text":"isa"
            },
            {
                "source":2,
                "target":1,
                "text":"wife",
                "type":"active"
            },
            {
                "source":2,
                "target":3,
                "text":"husband",
                "type":"active"
            },
            {
                "source":4,
                "target":5,
                "text":"isa"
            },
            {
                "source":6,
                "target":5,
                "text":"isa"
            },
            {
                "source":10,
                "target":8,
                "text":"isa"
            },
            {
                "source":11,
                "target":8,
                "text":"isa"
            },
            {
                "source":4,
                "target":1,
                "text":"director",
                "type":"active"
            },
            {
                "source":6,
                "target":3,
                "text":"director",
                "type":"active"
            },
            {
                "source":4,
                "target":7,
                "text":"directed",
                "type":"active"
            },
            {
                "source":6,
                "target":9,
                "text":"directed",
                "type":"active"
            },
            {
                "source":10,
                "target":7,
                "text":"houses",
                "type":"active"
            },
            {
                "source":11,
                "target":9,
                "text":"houses",
                "type":"active"
            },
            {
                "source":10,
                "target":12,
                "text":"location",
                "type":"active"
            },
            {
                "source":11,
                "target":12,
                "text":"location",
                "type":"active"
            }
        ]
    }
];