java_library(
    name = "api",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:com_eclipsesource_minimal_json_minimal_json",
        "@maven//:com_typesafe_akka_akka_actor_typed_2_12",
        "@maven//:com_typesafe_akka_akka_stream_2_12",
        "@maven//:com_typesafe_play_play_2_12",
        "@maven//:com_typesafe_play_play_java_2_12",
        "@maven//:com_typesafe_play_play_server_2_12",
        "@maven//:com_typesafe_play_play_streams_2_12",
        "@maven//:com_typesafe_play_twirl_api_2_12",
    ],
    visibility = ["//visibility:public"],
)
