insert
"knows" isa relation-type
	has-role person_1
	has-role person_2
	has-resource weight;
"person_1" ako acquaintance;
"person_2" ako acquaintance;

"created" isa relation-type
	has-role author
	has-role product
	has-resource weight;
"author" isa role-type;
"product" isa role-type;

"person" isa entity-type
	plays-role acquaintance
	plays-role author
	has-resource name
	has-resource age;

"software" isa entity-type
	plays-role product
	has-resource name
	has-resource lang;

"acquaintance" isa role-type is-abstract;

"weight" isa resource-type
	datatype double;

"name" isa resource-type
	datatype string;

"age" isa resource-type
	datatype long;

"lang" isa resource-type
	datatype string;

"node_1" isa person has name "marko" has age 29;
"node_2" isa person has name "vadas" has age 27;
"node_3" isa software has name "lop" has lang "java";
"node_4" isa person has name "josh" has age 32;
"node_5" isa software has name "ripple" has lang "java";
"node_6" isa person has name "peter" has age 35;

(person_1 node_1, person_2 node_2) isa knows has weight 0.5;
(person_1 node_1, person_2 node_4) isa knows has weight 1.0;
(author node_1, product node_3) isa created has weight 0.4;
(author node_4, product node_5) isa created has weight 1.0;
(author node_4, product node_3) isa created has weight 0.4;
(author node_6, product node_3) isa created has weight 0.2;