sh_binary(
    name = "setup-pages",
    srcs = ["setup-pages.sh"],
    deps = [],
    args = [
        "$(rootpath //pages:pages-dev)",
    ],
    data = [
        "//pages:pages-dev",
    ]
)

sh_binary(
    name = "setup-resources",
    srcs = ["setup-resources.sh"],
    deps = [],
)
